import { app, BrowserWindow, utilityProcess } from 'electron';
import type { ServerData } from '../types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const UTILITY_PROCESS_PATH: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let child = utilityProcess.fork(UTILITY_PROCESS_PATH);

const createWindow = (): void => {
    child.on("exit", () => child = utilityProcess.fork(UTILITY_PROCESS_PATH));
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            contextIsolation: true,
        },
    });
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    child.on("message", (data: ServerData) => {
        // Add message splitting so we can split for downloads
        mainWindow.webContents.send("url", data);
    });
};

app.on('ready', () => {
    createWindow();
});

app.on('window-all-closed', () => {
    if(process.platform !== "darwin") {
        app.quit();
    }
    child.kill();
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});